// swift-format-ignore-file
// GENERATED by scripts/gen-tokens.py from design/tokens.json. Do not edit.
import SwiftUI

public enum Tokens {
    public enum Palette {
        public static let background = Color(light: 0xF3F5F9FF, dark: 0x0A0C11FF)
        public static let surface = Color(light: 0xFFFFFFFF, dark: 0x12151CFF)
        public static let surfaceRaised = Color(light: 0xF8F9FCFF, dark: 0x191D26FF)
        public static let surfaceSunken = Color(light: 0xECEFF4FF, dark: 0x0E1117FF)
        public static let border = Color(light: 0x0F172A14, dark: 0xFFFFFF12)
        public static let borderStrong = Color(light: 0x0F172A26, dark: 0xFFFFFF24)
        public static let textPrimary = Color(light: 0x0F172AFF, dark: 0xF1F4F9FF)
        public static let textSecondary = Color(light: 0x475569FF, dark: 0x9AA4B6FF)
        public static let textTertiary = Color(light: 0x94A3B8FF, dark: 0x5F6B80FF)
        public static let accent = Color(light: 0x4F46E5FF, dark: 0x818CF8FF)
        public static let success = Color(light: 0x059669FF, dark: 0x34D399FF)
        public static let warning = Color(light: 0xD97706FF, dark: 0xFBBF24FF)
        public static let danger = Color(light: 0xDC2626FF, dark: 0xF87171FF)
        public static let chartGrid = Color(light: 0x0F172A0F, dark: 0xFFFFFF0D)
        public static let track = Color(light: 0x0F172A0F, dark: 0xFFFFFF0F)
    }

    public enum MetricPalette {
        public static let cpu = MetricStyle(start: Color(hex: 0x3B82F6FF), end: Color(hex: 0x22D3EEFF), symbol: "cpu")
        public static let memory = MetricStyle(start: Color(hex: 0x8B5CF6FF), end: Color(hex: 0xEC4899FF), symbol: "memorychip")
        public static let disk = MetricStyle(start: Color(hex: 0xF59E0BFF), end: Color(hex: 0xF97316FF), symbol: "internaldrive")
        public static let network = MetricStyle(start: Color(hex: 0x10B981FF), end: Color(hex: 0x84CC16FF), symbol: "network")
        public static let gpu = MetricStyle(start: Color(hex: 0xF43F5EFF), end: Color(hex: 0xFB923CFF), symbol: "cube.transparent")
    }

    public enum Space {
        public static let xxs: CGFloat = 2
        public static let xs: CGFloat = 4
        public static let sm: CGFloat = 8
        public static let md: CGFloat = 12
        public static let lg: CGFloat = 16
        public static let xl: CGFloat = 24
        public static let xxl: CGFloat = 32
        public static let xxxl: CGFloat = 48
    }

    public enum Radius {
        public static let xs: CGFloat = 4
        public static let sm: CGFloat = 6
        public static let md: CGFloat = 10
        public static let lg: CGFloat = 14
        public static let xl: CGFloat = 20
        public static let pill: CGFloat = 999
    }

    public enum Typography {
        public static let display = Font.system(size: 34, weight: .bold, design: .rounded)
        public static let title = Font.system(size: 22, weight: .semibold, design: .rounded)
        public static let headline = Font.system(size: 13, weight: .semibold, design: .default)
        public static let body = Font.system(size: 13, weight: .regular, design: .default)
        public static let label = Font.system(size: 11, weight: .medium, design: .default)
        public static let caption = Font.system(size: 10, weight: .medium, design: .default)
        public static let metric = Font.system(size: 28, weight: .semibold, design: .rounded)
        public static let mono = Font.system(size: 12, weight: .regular, design: .monospaced)
    }

    public enum Motion {
        public static let fast: Double = 0.15
        public static let normal: Double = 0.3
        public static let slow: Double = 0.6
    }

    public enum Chart {
        public static let lineWidth: CGFloat = 1.75
        public static let fillOpacityTop: CGFloat = 0.38
        public static let fillOpacityBottom: CGFloat = 0.0
        public static let glowRadius: CGFloat = 6
        public static let gaugeLineWidth: CGFloat = 10
    }

    public enum Shadow {
        public static let card = ShadowStyle(light: .init(color: Color(hex: 0x0F172AFF), opacity: 0.06, radius: 12, y: 4), dark: .init(color: Color(hex: 0x000000FF), opacity: 0.35, radius: 16, y: 6))
    }
}
