// GENERATED by scripts/gen-tokens.py from design/tokens.json. Do not edit.
#pragma once
#include <cstdint>

namespace procyon::tokens {

// Colors are 0xRRGGBBAA.
struct ColorPair {
    uint32_t light;
    uint32_t dark;
};

struct MetricStyle {
    uint32_t start;
    uint32_t end;
    const char *symbol;
};

enum class FontDesign { Default, Rounded, Monospaced };

struct FontSpec {
    float size;
    int weight;  // DirectWrite weight: 400 regular, 500 medium, 600 semibold, 700 bold
    FontDesign design;
};

struct ShadowSpec {
    uint32_t color;
    float opacity;
    float radius;
    float y;
};

struct ShadowStyle {
    ShadowSpec light;
    ShadowSpec dark;
};

namespace palette {
constexpr ColorPair background{0xF3F5F9FF, 0x0A0C11FF};
constexpr ColorPair surface{0xFFFFFFFF, 0x12151CFF};
constexpr ColorPair surfaceRaised{0xF8F9FCFF, 0x191D26FF};
constexpr ColorPair surfaceSunken{0xECEFF4FF, 0x0E1117FF};
constexpr ColorPair border{0x0F172A14, 0xFFFFFF12};
constexpr ColorPair borderStrong{0x0F172A26, 0xFFFFFF24};
constexpr ColorPair textPrimary{0x0F172AFF, 0xF1F4F9FF};
constexpr ColorPair textSecondary{0x475569FF, 0x9AA4B6FF};
constexpr ColorPair textTertiary{0x94A3B8FF, 0x5F6B80FF};
constexpr ColorPair accent{0x4F46E5FF, 0x818CF8FF};
constexpr ColorPair success{0x059669FF, 0x34D399FF};
constexpr ColorPair warning{0xD97706FF, 0xFBBF24FF};
constexpr ColorPair danger{0xDC2626FF, 0xF87171FF};
constexpr ColorPair chartGrid{0x0F172A0F, 0xFFFFFF0D};
constexpr ColorPair track{0x0F172A0F, 0xFFFFFF0F};
}  // namespace palette

namespace metric {
constexpr MetricStyle cpu{0x3B82F6FF, 0x22D3EEFF, "cpu"};
constexpr MetricStyle memory{0x8B5CF6FF, 0xEC4899FF, "memorychip"};
constexpr MetricStyle disk{0xF59E0BFF, 0xF97316FF, "internaldrive"};
constexpr MetricStyle network{0x10B981FF, 0x84CC16FF, "network"};
constexpr MetricStyle gpu{0xF43F5EFF, 0xFB923CFF, "cube.transparent"};
constexpr MetricStyle battery{0xA3E635FF, 0x22C55EFF, "battery.100percent"};
constexpr MetricStyle energy{0xFACC15FF, 0xA3E635FF, "bolt.fill"};
}  // namespace metric

namespace space {
constexpr float xxs = 2;
constexpr float xs = 4;
constexpr float sm = 8;
constexpr float md = 12;
constexpr float lg = 16;
constexpr float xl = 24;
constexpr float xxl = 32;
constexpr float xxxl = 48;
}  // namespace space

namespace radius {
constexpr float xs = 4;
constexpr float sm = 6;
constexpr float md = 10;
constexpr float lg = 14;
constexpr float xl = 20;
constexpr float pill = 999;
}  // namespace radius

namespace font {
constexpr FontSpec display{34, 700, FontDesign::Rounded};
constexpr FontSpec title{22, 600, FontDesign::Rounded};
constexpr FontSpec headline{13, 600, FontDesign::Default};
constexpr FontSpec body{13, 400, FontDesign::Default};
constexpr FontSpec label{11, 500, FontDesign::Default};
constexpr FontSpec caption{10, 500, FontDesign::Default};
constexpr FontSpec metric{28, 600, FontDesign::Rounded};
constexpr FontSpec mono{12, 400, FontDesign::Monospaced};
}  // namespace font

namespace motion {
constexpr float fast = 0.15f;
constexpr float normal = 0.3f;
constexpr float slow = 0.6f;
}  // namespace motion

namespace chart {
constexpr float lineWidth = 1.75f;
constexpr float fillOpacityTop = 0.38f;
constexpr float fillOpacityBottom = 0.0f;
constexpr float glowRadius = 6;
constexpr float gaugeLineWidth = 10;
}  // namespace chart

namespace shadow {
constexpr ShadowStyle card{{0x0F172AFF, 0.06f, 12, 4}, {0x000000FF, 0.35f, 16, 6}};
}  // namespace shadow

}  // namespace procyon::tokens
