#!/usr/bin/env python3
"""Generate platform process catalogs from data/process-catalog.json.

Currently emits Swift (macOS); the Windows and Linux UIs get their emitters here too.

    python3 scripts/gen-catalog.py          # write
    python3 scripts/gen-catalog.py --check  # exit 1 if the committed file is stale (CI)
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOG = json.loads((ROOT / "data" / "process-catalog.json").read_text(encoding="utf-8"))
SWIFT_OUT = ROOT / "apps/macos/Sources/ProcyonKit/ProcessCatalog.generated.swift"
ADVICE = {"keep": ".keep", "restarts": ".restarts", "quit": ".quit"}


def literal(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def swift() -> str:
    out = [
        "// swift-format-ignore-file",
        "// GENERATED by scripts/gen-catalog.py from data/process-catalog.json. Do not edit.",
        "",
        "extension ProcessCatalog {",
        "    static let entries: [String: ProcessExplanation] = {",
        "        var entries: [String: ProcessExplanation] = [:]",
    ]
    for index, entry in enumerate(CATALOG["macos"]):
        if entry["advice"] not in ADVICE:
            sys.exit(f"gen-catalog: unknown advice {entry['advice']!r} for {entry['names']}")
        out.append(
            f"        let e{index} = ProcessExplanation(advice: {ADVICE[entry['advice']]}, "
            f"summary: {literal(entry['description'])})"
        )
        for name in entry["names"]:
            out.append(f"        entries[{literal(name)}] = e{index}")
    out += ["        return entries", "    }()", "}", ""]
    return "\n".join(out)


def main() -> None:
    generated = swift()
    if "--check" in sys.argv:
        if not SWIFT_OUT.exists() or SWIFT_OUT.read_text(encoding="utf-8") != generated:
            sys.exit("ProcessCatalog.generated.swift is stale: run `python3 scripts/gen-catalog.py`")
        return
    SWIFT_OUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"wrote {SWIFT_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
