#!/usr/bin/env python3
"""Generate platform token files from design/tokens.json.

Currently emits SwiftUI (macOS). Windows (Win32) and Linux (GTK CSS) emitters
belong here too, so every UI reads the same values.

    python3 scripts/gen-tokens.py          # write
    python3 scripts/gen-tokens.py --check  # exit 1 if the committed file is stale (CI)
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOKENS = json.loads((ROOT / "design" / "tokens.json").read_text())
SWIFT_OUT = ROOT / "apps/macos/Sources/ProcyonDesign/Tokens/Tokens.generated.swift"


def hex_literal(value: str) -> str:
    """'#RRGGBB' or '#RRGGBBAA' -> '0xRRGGBBAA'."""
    value = value.lstrip("#")
    if len(value) == 6:
        value += "FF"
    return "0x" + value.upper()


def swift() -> str:
    out = [
        "// swift-format-ignore-file",
        "// GENERATED by scripts/gen-tokens.py from design/tokens.json. Do not edit.",
        "import SwiftUI",
        "",
        "public enum Tokens {",
        "    public enum Palette {",
    ]
    for name, pair in TOKENS["color"].items():
        out.append(
            f"        public static let {name} = Color(light: {hex_literal(pair['light'])}, dark: {hex_literal(pair['dark'])})"
        )
    out += ["    }", "", "    public enum MetricPalette {"]
    for name, spec in TOKENS["metric"].items():
        out.append(
            f"        public static let {name} = MetricStyle(start: Color(hex: {hex_literal(spec['start'])}), "
            f"end: Color(hex: {hex_literal(spec['end'])}), symbol: \"{spec['symbol']}\")"
        )
    out += ["    }", "", "    public enum Space {"]
    for name, value in TOKENS["space"].items():
        out.append(f"        public static let {name}: CGFloat = {value}")
    out += ["    }", "", "    public enum Radius {"]
    for name, value in TOKENS["radius"].items():
        out.append(f"        public static let {name}: CGFloat = {value}")
    out += ["    }", "", "    public enum Typography {"]
    for name, spec in TOKENS["font"].items():
        out.append(
            f"        public static let {name} = Font.system(size: {spec['size']}, weight: .{spec['weight']}, design: .{spec['design']})"
        )
    out += ["    }", "", "    public enum Motion {"]
    for name, value in TOKENS["motion"].items():
        out.append(f"        public static let {name}: Double = {value}")
    out += ["    }", "", "    public enum Chart {"]
    for name, value in TOKENS["chart"].items():
        out.append(f"        public static let {name}: CGFloat = {value}")
    out += ["    }", "", "    public enum Shadow {"]
    for name, modes in TOKENS["shadow"].items():
        light, dark = modes["light"], modes["dark"]
        out.append(
            f"        public static let {name} = ShadowStyle("
            f"light: .init(color: Color(hex: {hex_literal(light['color'])}), opacity: {light['opacity']}, radius: {light['radius']}, y: {light['y']}), "
            f"dark: .init(color: Color(hex: {hex_literal(dark['color'])}), opacity: {dark['opacity']}, radius: {dark['radius']}, y: {dark['y']}))"
        )
    out += ["    }", "}", ""]
    return "\n".join(out)


if __name__ == "__main__":
    generated = swift()
    if "--check" in sys.argv:
        if not SWIFT_OUT.exists() or SWIFT_OUT.read_text() != generated:
            print(f"{SWIFT_OUT.relative_to(ROOT)} is stale: run scripts/gen-tokens.py", file=sys.stderr)
            sys.exit(1)
        sys.exit(0)
    SWIFT_OUT.parent.mkdir(parents=True, exist_ok=True)
    SWIFT_OUT.write_text(generated)
    print(f"wrote {SWIFT_OUT.relative_to(ROOT)}")
