#!/usr/bin/env python3
"""Generate platform token files from design/tokens.json.

Emits SwiftUI (macOS) and a C++ header for the shared UI of the other platforms (apps/ui, used by
the Windows and Linux apps), so every UI reads the same values.

    python3 scripts/gen-tokens.py          # write
    python3 scripts/gen-tokens.py --check  # exit 1 if a committed file is stale (CI)
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TOKENS = json.loads((ROOT / "design" / "tokens.json").read_text(encoding="utf-8"))
SWIFT_OUT = ROOT / "apps/macos/Sources/ProcyonDesign/Tokens/Tokens.generated.swift"
UI_OUT = ROOT / "apps/ui/src/Tokens.generated.h"

# DirectWrite weights for the token names.
WEIGHTS = {"regular": 400, "medium": 500, "semibold": 600, "bold": 700}


def cpp_number(value) -> str:
    """Floats get the f suffix so MSVC does not warn about double-to-float truncation."""
    return f"{value}f" if isinstance(value, float) else str(value)


def hex_literal(value: str) -> str:
    """'#RRGGBB' or '#RRGGBBAA' -> '0xRRGGBBAA'."""
    value = value.lstrip("#")
    if len(value) == 6:
        value += "FF"
    return "0x" + value.upper()


def swift() -> str:
    out = [
        "// swift-format-ignore-file",
        "// GENERATED by scripts/gen-tokens.py from design/tokens.json. Do not edit.",
        "import SwiftUI",
        "",
        "public enum Tokens {",
        "    public enum Palette {",
    ]
    for name, pair in TOKENS["color"].items():
        out.append(
            f"        public static let {name} = Color(light: {hex_literal(pair['light'])}, dark: {hex_literal(pair['dark'])})"
        )
    out += ["    }", "", "    public enum MetricPalette {"]
    for name, spec in TOKENS["metric"].items():
        out.append(
            f"        public static let {name} = MetricStyle(start: Color(hex: {hex_literal(spec['start'])}), "
            f"end: Color(hex: {hex_literal(spec['end'])}), symbol: \"{spec['symbol']}\")"
        )
    out += ["    }", "", "    public enum Space {"]
    for name, value in TOKENS["space"].items():
        out.append(f"        public static let {name}: CGFloat = {value}")
    out += ["    }", "", "    public enum Radius {"]
    for name, value in TOKENS["radius"].items():
        out.append(f"        public static let {name}: CGFloat = {value}")
    out += ["    }", "", "    public enum Typography {"]
    for name, spec in TOKENS["font"].items():
        out.append(
            f"        public static let {name} = Font.system(size: {spec['size']}, weight: .{spec['weight']}, design: .{spec['design']})"
        )
    out += ["    }", "", "    public enum Motion {"]
    for name, value in TOKENS["motion"].items():
        out.append(f"        public static let {name}: Double = {value}")
    out += ["    }", "", "    public enum Chart {"]
    for name, value in TOKENS["chart"].items():
        out.append(f"        public static let {name}: CGFloat = {value}")
    out += ["    }", "", "    public enum Shadow {"]
    for name, modes in TOKENS["shadow"].items():
        light, dark = modes["light"], modes["dark"]
        out.append(
            f"        public static let {name} = ShadowStyle("
            f"light: .init(color: Color(hex: {hex_literal(light['color'])}), opacity: {light['opacity']}, radius: {light['radius']}, y: {light['y']}), "
            f"dark: .init(color: Color(hex: {hex_literal(dark['color'])}), opacity: {dark['opacity']}, radius: {dark['radius']}, y: {dark['y']}))"
        )
    out += ["    }", "}", ""]
    return "\n".join(out)


def windows() -> str:
    out = [
        "// GENERATED by scripts/gen-tokens.py from design/tokens.json. Do not edit.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace procyon::tokens {",
        "",
        "// Colors are 0xRRGGBBAA.",
        "struct ColorPair {",
        "    uint32_t light;",
        "    uint32_t dark;",
        "};",
        "",
        "struct MetricStyle {",
        "    uint32_t start;",
        "    uint32_t end;",
        "    const char *symbol;",
        "};",
        "",
        "enum class FontDesign { Default, Rounded, Monospaced };",
        "",
        "struct FontSpec {",
        "    float size;",
        "    int weight;  // DirectWrite weight: 400 regular, 500 medium, 600 semibold, 700 bold",
        "    FontDesign design;",
        "};",
        "",
        "struct ShadowSpec {",
        "    uint32_t color;",
        "    float opacity;",
        "    float radius;",
        "    float y;",
        "};",
        "",
        "struct ShadowStyle {",
        "    ShadowSpec light;",
        "    ShadowSpec dark;",
        "};",
        "",
        "namespace palette {",
    ]
    for name, pair in TOKENS["color"].items():
        out.append(f"constexpr ColorPair {name}{{{hex_literal(pair['light'])}, {hex_literal(pair['dark'])}}};")
    out += ["}  // namespace palette", "", "namespace metric {"]
    for name, spec in TOKENS["metric"].items():
        out.append(
            f"constexpr MetricStyle {name}{{{hex_literal(spec['start'])}, {hex_literal(spec['end'])}, \"{spec['symbol']}\"}};"
        )
    out += ["}  // namespace metric", "", "namespace space {"]
    for name, value in TOKENS["space"].items():
        out.append(f"constexpr float {name} = {value};")
    out += ["}  // namespace space", "", "namespace radius {"]
    for name, value in TOKENS["radius"].items():
        out.append(f"constexpr float {name} = {value};")
    out += ["}  // namespace radius", "", "namespace font {"]
    for name, spec in TOKENS["font"].items():
        design = spec["design"].capitalize()
        out.append(f"constexpr FontSpec {name}{{{spec['size']}, {WEIGHTS[spec['weight']]}, FontDesign::{design}}};")
    out += ["}  // namespace font", "", "namespace motion {"]
    for name, value in TOKENS["motion"].items():
        out.append(f"constexpr float {name} = {cpp_number(value)};")
    out += ["}  // namespace motion", "", "namespace chart {"]
    for name, value in TOKENS["chart"].items():
        out.append(f"constexpr float {name} = {cpp_number(value)};")
    out += ["}  // namespace chart", "", "namespace shadow {"]
    for name, modes in TOKENS["shadow"].items():
        light, dark = modes["light"], modes["dark"]
        out.append(
            f"constexpr ShadowStyle {name}{{{{{hex_literal(light['color'])}, {cpp_number(light['opacity'])}, {cpp_number(light['radius'])}, {cpp_number(light['y'])}}}, "
            f"{{{hex_literal(dark['color'])}, {cpp_number(dark['opacity'])}, {cpp_number(dark['radius'])}, {cpp_number(dark['y'])}}}}};"
        )
    out += ["}  // namespace shadow", "", "}  // namespace procyon::tokens", ""]
    return "\n".join(out)


OUTPUTS = [(SWIFT_OUT, swift), (UI_OUT, windows)]

if __name__ == "__main__":
    stale = False
    for path, emit in OUTPUTS:
        generated = emit()
        if "--check" in sys.argv:
            if not path.exists() or path.read_text(encoding="utf-8") != generated:
                print(f"{path.relative_to(ROOT)} is stale: run scripts/gen-tokens.py", file=sys.stderr)
                stale = True
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(generated, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        sys.exit(1)
